included:

excluded:
  - Derived
  - DerivedData
  - "**/generated"
  - "**/.build"
  - "**/*Tests.swift"

opt_in_rules:
  - array_init
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - convenience_type
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_count
  - empty_string
  - empty_xctest_method
  - explicit_init
  - fallthrough
  - fatal_error_message
  - file_name
  - file_types_order
  - first_where
  - force_unwrapping
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - number_separator
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - private_action
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - single_test_class
  - sorted_first_last
  - static_operator
  - strong_iboutlet
  - toggle_bool
  - type_contents_order
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - xct_specific_matcher
  - yoda_condition
disabled_rules:
  - todo
  - blanket_disable_command
  - file_name
  - untyped_error_in_catch
  - type_name
  - type_contents_order
  - comment_spacing
  - file_types_order
  - lower_acl_than_parent
  - let_var_whitespace
  - line_length
  
identifier_name:
  excluded:
    - id
modifier_order:
  preferred_modifier_order:
    - acl
    - setterACL
    - override
    - dynamic
    - mutators
    - lazy
    - final
    - required
    - convenience
    - typeMethods
    - owned
nesting:
  type_level:
    warning: 3
number_separator:
  minimum_fraction_length: 10
trailing_whitespace:
  ignores_empty_lines: true
implicit_return:
  included:
    - closure
    - getter

closure_body_length: 100

custom_rules:

  print_expression:
    name: "Unexpected print expression"
    message: "print should not be used for logging. Use `log`"
    regex: 'print\(".+?"\)'
    severity: warning
